### ISSUE TITLE
CSS: Improve landing page layout

### ISSUE THREAD

**Issue by ionescu77** [ionescu77/myWebsite2#201]
## Hero image full viewport

- [x] move img to css
- [x] make carousel section full screen (full viewport)
- [x]  see here

https://github.com/ionescu77/myWebsite2/blob/ec3f3b156ecff881a4b5604c571de3a22a693d3d/src/templates/includes/base.html#L83

**Comment by ionescu77** [comment]
## Example avproiect.com


```html
    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">Software Architects</div>
                <div class="intro-heading">We Make Your Life <span style="color: orange">Easy</span></div>
                <a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>
            </div>
        </div>
    </header>
```



```css
header {
    background-color: rgb(0, 0, 0);
    background-image: url(../img/software-architects.avproiect.com.jpg);
    min-height: 100vh;  /* 100% viewport height */
}
```
