### ISSUE TITLE
Dependabot ignore major versions

### ISSUE THREAD

**Issue by ionescu77** [ionescu77/myWebsite2#470]
## Dependabot stick to LTS
Make dependabot stick to django LTS version

## Alternative
```yaml
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
```

https://stackoverflow.com/questions/60649404/how-can-i-change-my-dependabot-config-to-exclude-major-versions?rq=2

## Current

```yaml
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
```
