### ISSUE TITLE
TEST: Jenkins Django Matrix

### ISSUE THREAD

**Issue by ionescu77** [ionescu77/myWebsite2#81]
Implement django matrix for jenkins test, to prepare for django upgrade.

- [ ] move django out of `requirements/test.txt`
- [ ] implement jenkins matrix for versions of interest

- `travis.yml` matrix example:

```yml
sudo: false
language: python
cache: pip

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7-dev"

env:
  matrix:
   - DJANGO="Django<1.12"
   - DJANGO="Django<2.1"
   - DJANGO="Django<2.2"
   - DJANGO="Django<2.3"

install:
 - pip install --upgrade pip wheel setuptools
 - pip install coverage flake8
 - pip install "$DJANGO"
 - pip install -r requirements.txt
 - pip install .

matrix:
  fast_finish: true

  exclude:
    # Supported Django/Python versions - https://docs.djangoproject.com/en/2.1/faq/install/
    # Latest Django 1.11
    - { python: "3.7-dev", env: DJANGO="Django<1.12" }
    # Latest Django 2.0
    - { python: "2.7", env: DJANGO="Django<2.1" }
    # Latest Django 2.1
    - { python: "2.7", env: DJANGO="Django<2.2" }
    - { python: "3.4", env: DJANGO="Django<2.2" }
    # Latest Django 2.2
    - { python: "2.7", env: DJANGO="Django<2.3" }
    - { python: "3.4", env: DJANGO="Django<2.3" }

  allow_failures:
    - python: 3.7-dev

branches:
 only:
  - master
  - dev

script:
  - flake8 health_monitor
  - flake8 test
  - coverage run manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
```
